# Generated by Django 5.0.4 on 2025-01-05 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profile_picture', models.FileField(max_length=400, null=True, upload_to='')),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('bio', models.TextField(max_length=150, null=True)),
                ('Dob', models.DateField(null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('mobile', models.IntegerField(max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_file', models.FileField(max_length=400, upload_to='')),
                ('post_description', models.TextField(max_length=150)),
                ('post_created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.profile')),
            ],
        ),
    ]
